### ISSUE TITLE
comments.js ajax, requirejs

### ISSUE THREAD

**Issue by grekpg** [FriendsOfSymfony/FOSCommentBundle#644] opened 2018-02-28 09:12 UTC
Why comments.js use globals ? if i use dialogs , load new content comments stop working.
Its possible to use comments.js with requirejs ?

**Comment by XWB** [comment] 2018-05-16 10:05
Duplicate of https://github.com/FriendsOfSymfony/FOSCommentBundle/issues/637

**Closed by XWB** 2018-05-16 10:05 UTC
